// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson8915695aDecodeAppInternalParkingModel(in *jlexer.Lexer, out *Response) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(Response, 0, 0)
			} else {
				*out = Response{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 Parking
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8915695aEncodeAppInternalParkingModel(out *jwriter.Writer, in Response) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v Response) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8915695aEncodeAppInternalParkingModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Response) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8915695aEncodeAppInternalParkingModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Response) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8915695aDecodeAppInternalParkingModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Response) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8915695aDecodeAppInternalParkingModel(l, v)
}
func easyjson8915695aDecodeAppInternalParkingModel1(in *jlexer.Lexer, out *Parking) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "dislocation":
			out.Dislocation = string(in.String())
		case "traffic_signs":
			out.TrafficSigns = string(in.String())
		case "street":
			out.Street = string(in.String())
		case "seats":
			out.Seats = string(in.String())
		case "stopping":
			out.Stopping = string(in.String())
		case "parking_bay":
			out.ParkingBay = string(in.String())
		case "avenue":
			out.Avenue = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson8915695aEncodeAppInternalParkingModel1(out *jwriter.Writer, in Parking) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"dislocation\":"
		out.RawString(prefix)
		out.String(string(in.Dislocation))
	}
	{
		const prefix string = ",\"traffic_signs\":"
		out.RawString(prefix)
		out.String(string(in.TrafficSigns))
	}
	if in.Street != "" {
		const prefix string = ",\"street\":"
		out.RawString(prefix)
		out.String(string(in.Street))
	}
	{
		const prefix string = ",\"seats\":"
		out.RawString(prefix)
		out.String(string(in.Seats))
	}
	{
		const prefix string = ",\"stopping\":"
		out.RawString(prefix)
		out.String(string(in.Stopping))
	}
	{
		const prefix string = ",\"parking_bay\":"
		out.RawString(prefix)
		out.String(string(in.ParkingBay))
	}
	if in.Avenue != "" {
		const prefix string = ",\"avenue\":"
		out.RawString(prefix)
		out.String(string(in.Avenue))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Parking) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson8915695aEncodeAppInternalParkingModel1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Parking) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson8915695aEncodeAppInternalParkingModel1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Parking) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson8915695aDecodeAppInternalParkingModel1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Parking) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson8915695aDecodeAppInternalParkingModel1(l, v)
}
